language: node_js
before_install:
  - "npm install -d && npm run build"
node_js:
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.10"
  - "iojs"
notificiations:
  email:
    on_fail: never
    on_success: never
    on_change: never
