dist: trusty
sudo: required
language: node_js
node_js:
- "lts/*"
- "11.10"

os:
- linux

jobs:
  include:
  - stage: install
    script: npm install
    skip_cleanup: true
  - stage: test
    script: npm run coverage
    skip_cleanup: true
  - stage: release
    node_js: lts/*
    deploy:
      provider: script
      skip_cleanup: true
      script:
      - npx semantic-release
    if: branch = master
