language: node_js
notificiations:
  email: false
env:
  global:
    - NODE_ENV=development
jobs:
  include:
  - stage: install
    script: npm install
    node_js:
      - "11.10"
      - "11.0"
      - "10.15.2"
      - "10.13"
      - "10.0"
    skip_cleanup: true
  - stage: test
    script: npm run coveralls
    skip_cleanup: true
  - stage: release
    node_js:
      - "11.10"
      - "11.0"
      - "10.15.2"
      - "10.13"
      - "10.0"
    deploy:
      provider: script
      skip_cleanup: true
      script:
      - npx semantic-release
    if: branch = master
# script:
#   - npm run coveralls